### ISSUE TITLE
Compilation error: Cannot find symbol class BandwidthResource

### ISSUE THREAD

**Issue by srijanmishra** [opennetworkinglab/onos-app-samples#1]
While installing the app samples using `mvn clean install` following error is generated. It seems wrong class is being imported or am I missing something?

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project onos-app-calendar: Compilation failure: Compilation failure:
> [ERROR] /home/srijan/projects/gsoc15/onos-app-samples/calendar/src/main/java/org/onosproject/calendar/BandwidthCalendarResource.java:[42,35] error: cannot find symbol
> [ERROR] symbol:   class BandwidthResource
> [ERROR] location: package org.onosproject.net.resource
> [ERROR] /home/srijan/projects/gsoc15/onos-app-samples/calendar/src/main/java/org/onosproject/calendar/BandwidthCalendarResource.java:[225,44] error: cannot find symbol
> [ERROR] -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project onos-app-calendar: Compilation failure
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
>     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
>     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
>     at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
>     at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
>     at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
> Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
>     at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:729)
>     at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
>     ... 20 more

**Comment by srijanmishra** [comment]
Fixed by c6deaaa03817703fc8156a71d664dc307cb327d9
